# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt4 UI code generator 4.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import QTermWidget

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1060, 620)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(1,1,1,1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setContentsMargins(1,1,1,1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(2)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setContentsMargins(1,1,1,1)
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(1,1,1,1)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setMaximumSize(QtCore.QSize(70, 15))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_7.addWidget(self.label_4)
        self.CBRuleAll = QtWidgets.QCheckBox(self.groupBox_4)
        self.CBRuleAll.setMaximumSize(QtCore.QSize(80, 15))
        self.CBRuleAll.setChecked(False)
        self.CBRuleAll.setObjectName(_fromUtf8("CBRuleAll"))
        self.horizontalLayout_7.addWidget(self.CBRuleAll)
        self.CBRulePE = QtWidgets.QCheckBox(self.groupBox_4)
        self.CBRulePE.setMaximumSize(QtCore.QSize(100, 15))
        self.CBRulePE.setObjectName(_fromUtf8("CBRulePE"))
        self.horizontalLayout_7.addWidget(self.CBRulePE)
        self.CBRuleCrypto = QtWidgets.QCheckBox(self.groupBox_4)
        self.CBRuleCrypto.setMaximumSize(QtCore.QSize(120, 15))
        self.CBRuleCrypto.setObjectName(_fromUtf8("CBRuleCrypto"))
        self.horizontalLayout_7.addWidget(self.CBRuleCrypto)
        self.CBRulePack = QtWidgets.QCheckBox(self.groupBox_4)
        self.CBRulePack.setMaximumSize(QtCore.QSize(120, 15))
        self.CBRulePack.setObjectName(_fromUtf8("CBRulePack"))
        self.horizontalLayout_7.addWidget(self.CBRulePack)
        self.CBRuleSelf = QtWidgets.QCheckBox(self.groupBox_4)
        self.CBRuleSelf.setMaximumSize(QtCore.QSize(140, 15))
        self.CBRuleSelf.setObjectName(_fromUtf8("CBRuleSelf"))
        self.horizontalLayout_7.addWidget(self.CBRuleSelf)
        self.CBRuleWL = QtWidgets.QCheckBox(self.groupBox_4)
        self.CBRuleWL.setMaximumSize(QtCore.QSize(140, 15))
        self.CBRuleWL.setObjectName(_fromUtf8("CBRuleWL"))
        self.horizontalLayout_7.addWidget(self.CBRuleWL)
        self.horizontalLayout_7.setStretch(0, 2)
        self.horizontalLayout_7.setStretch(1, 1)
        self.horizontalLayout_7.setStretch(2, 1)
        self.horizontalLayout_7.setStretch(3, 1)
        self.horizontalLayout_7.setStretch(4, 1)
        self.horizontalLayout_7.setStretch(5, 1)
        self.horizontalLayout_7.setStretch(6, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(1, 1, 2, 1)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setMaximumSize(QtCore.QSize(70, 15))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_6.addWidget(self.label_3)
        self.CBTypeAll = QtWidgets.QCheckBox(self.groupBox_4)
        self.CBTypeAll.setMaximumSize(QtCore.QSize(80, 15))
        self.CBTypeAll.setChecked(False)
        self.CBTypeAll.setObjectName(_fromUtf8("CBTypeAll"))
        self.horizontalLayout_6.addWidget(self.CBTypeAll)
        self.CBTypePE = QtWidgets.QCheckBox(self.groupBox_4)
        self.CBTypePE.setMaximumSize(QtCore.QSize(50, 15))
        self.CBTypePE.setChecked(True)
        self.CBTypePE.setObjectName(_fromUtf8("CBTypePE"))
        self.horizontalLayout_6.addWidget(self.CBTypePE)
        self.CBTypeOffice = QtWidgets.QCheckBox(self.groupBox_4)
        self.CBTypeOffice.setMaximumSize(QtCore.QSize(100, 15))
        self.CBTypeOffice.setObjectName(_fromUtf8("CBTypeOffice"))
        self.horizontalLayout_6.addWidget(self.CBTypeOffice)
        self.CBTypeShell = QtWidgets.QCheckBox(self.groupBox_4)
        self.CBTypeShell.setMaximumSize(QtCore.QSize(80, 15))
        self.CBTypeShell.setObjectName(_fromUtf8("CBTypeShell"))
        self.horizontalLayout_6.addWidget(self.CBTypeShell)
        self.CBTypeZip = QtWidgets.QCheckBox(self.groupBox_4)
        self.CBTypeZip.setMaximumSize(QtCore.QSize(95, 15))
        self.CBTypeZip.setObjectName(_fromUtf8("CBTypeZip"))
        self.horizontalLayout_6.addWidget(self.CBTypeZip)
        self.CBTypeMedia = QtWidgets.QCheckBox(self.groupBox_4)
        self.CBTypeMedia.setMaximumSize(QtCore.QSize(95, 15))
        self.CBTypeMedia.setObjectName(_fromUtf8("CBTypeMedia"))
        self.horizontalLayout_6.addWidget(self.CBTypeMedia)
        self.CBTypeAsm = QtWidgets.QCheckBox(self.groupBox_4)
        self.CBTypeAsm.setMaximumSize(QtCore.QSize(110, 15))
        self.CBTypeAsm.setObjectName(_fromUtf8("CBTypeAsm"))
        self.horizontalLayout_6.addWidget(self.CBTypeAsm)
        self.horizontalLayout_6.setStretch(0, 2)
        self.horizontalLayout_6.setStretch(1, 1)
        self.horizontalLayout_6.setStretch(2, 1)
        self.horizontalLayout_6.setStretch(3, 1)
        self.horizontalLayout_6.setStretch(4, 1)
        self.horizontalLayout_6.setStretch(5, 1)
        self.horizontalLayout_6.setStretch(6, 1)
        self.horizontalLayout_6.setStretch(7, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(1, 1, 6, 1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setMaximumSize(QtCore.QSize(70, 15))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.lineEditAdvSet = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEditAdvSet.setObjectName(_fromUtf8("lineEditAdvSet"))
        self.horizontalLayout.addWidget(self.lineEditAdvSet)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_9.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(260, 100))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setContentsMargins(3, 1, 3, 1)
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEditScanStart = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditScanStart.sizePolicy().hasHeightForWidth())
        self.lineEditScanStart.setSizePolicy(sizePolicy)
        self.lineEditScanStart.setObjectName(_fromUtf8("lineEditScanStart"))
        self.horizontalLayout_3.addWidget(self.lineEditScanStart)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 21))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_6.setStatusTip(_fromUtf8(""))
        self.label_6.setWhatsThis(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox.setSuffix(_fromUtf8(""))
        self.spinBox.setPrefix(_fromUtf8(""))
        self.spinBox.setMinimum(-1)
        self.spinBox.setProperty("value", -1)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.horizontalLayout_4.addWidget(self.spinBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.PB_SelectFolder = QtWidgets.QPushButton(self.groupBox_3)
        self.PB_SelectFolder.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.PB_SelectFolder.setObjectName(_fromUtf8("PB_SelectFolder"))
        self.horizontalLayout_5.addWidget(self.PB_SelectFolder)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.PB_Start = QtWidgets.QPushButton(self.groupBox_3)
        self.PB_Start.setObjectName(_fromUtf8("PB_Start"))
        self.horizontalLayout_5.addWidget(self.PB_Start)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.PB_End = QtWidgets.QPushButton(self.groupBox_3)
        self.PB_End.setObjectName(_fromUtf8("PB_End"))
        self.horizontalLayout_5.addWidget(self.PB_End)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setContentsMargins(3, 1, 3, 1)
        self.verticalLayout_7.setSpacing(3)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_8.addWidget(self.label_7)
        self.lineEditSelect = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditSelect.setObjectName(_fromUtf8("lineEditSelect"))
        self.horizontalLayout_8.addWidget(self.lineEditSelect)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_10.addWidget(self.label_8)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setMinimumSize(QtCore.QSize(0, 21))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.horizontalLayout_10.addWidget(self.comboBox_2)
        self.PB_Select = QtWidgets.QPushButton(self.groupBox)
        self.PB_Select.setObjectName(_fromUtf8("PB_Select"))
        self.horizontalLayout_10.addWidget(self.PB_Select)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.PB_Recover = QtWidgets.QPushButton(self.groupBox)
        self.PB_Recover.setObjectName(_fromUtf8("PB_Recover"))
        self.horizontalLayout_2.addWidget(self.PB_Recover)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.PB_Store = QtWidgets.QPushButton(self.groupBox)
        self.PB_Store.setObjectName(_fromUtf8("PB_Store"))
        self.horizontalLayout_2.addWidget(self.PB_Store)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.PB_Clear = QtWidgets.QPushButton(self.groupBox)
        self.PB_Clear.setObjectName(_fromUtf8("PB_Clear"))
        self.horizontalLayout_2.addWidget(self.PB_Clear)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_9.addWidget(self.groupBox)
        self.horizontalLayout_9.setStretch(0, 5)
        self.horizontalLayout_9.setStretch(1, 3)
        self.horizontalLayout_9.setStretch(2, 3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setMinimumSize(QtCore.QSize(450, 280))
        self.tableWidget.setToolTip(_fromUtf8(""))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(110)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_8.setContentsMargins(0,0,0,0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.textEdit = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_8.addWidget(self.textEdit)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem9)
        self.PB_KeepLog = QtWidgets.QPushButton(self.tab_2)
        self.PB_KeepLog.setObjectName(_fromUtf8("PB_KeepLog"))
        self.horizontalLayout_11.addWidget(self.PB_KeepLog)
        self.PB_ClearLog = QtWidgets.QPushButton(self.tab_2)
        self.PB_ClearLog.setObjectName(_fromUtf8("PB_ClearLog"))
        self.horizontalLayout_11.addWidget(self.PB_ClearLog)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_9.setContentsMargins(0,0,0,0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.calendarWidget = QtWidgets.QCalendarWidget(self.tab_3)
        self.calendarWidget.setObjectName(_fromUtf8("calendarWidget"))
        self.horizontalLayout_12.addWidget(self.calendarWidget)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_13.addWidget(self.label_9)
        self.LE_FuzzyHistory = QtWidgets.QLineEdit(self.groupBox_2)
        self.LE_FuzzyHistory.setObjectName(_fromUtf8("LE_FuzzyHistory"))
        self.horizontalLayout_13.addWidget(self.LE_FuzzyHistory)
        self.verticalLayout_10.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_14.addWidget(self.label_10)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.horizontalLayout_14.addWidget(self.comboBox_3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem10)
        self.PB_SelectHistory = QtWidgets.QPushButton(self.groupBox_2)
        self.PB_SelectHistory.setObjectName(_fromUtf8("PB_SelectHistory"))
        self.horizontalLayout_15.addWidget(self.PB_SelectHistory)
        self.verticalLayout_10.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_12.addWidget(self.groupBox_2)
        self.horizontalLayout_12.setStretch(0, 3)
        self.horizontalLayout_12.setStretch(1, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_12)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(8)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(110)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_9.addWidget(self.tableWidget_2)
        self.verticalLayout_9.setStretch(1, 3)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QTermWidget.QTermWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout.addWidget(self.progressBar)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1060, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName(_fromUtf8("menu_4"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.AC_Check = QtWidgets.QAction(MainWindow)
        self.AC_Check.setObjectName(_fromUtf8("AC_Check"))
        self.AC_Setting = QtWidgets.QAction(MainWindow)
        self.AC_Setting.setObjectName(_fromUtf8("AC_Setting"))
        self.AC_CheckML = QtWidgets.QAction(MainWindow)
        self.AC_CheckML.setObjectName(_fromUtf8("AC_CheckML"))
        self.AC_Info = QtWidgets.QAction(MainWindow)
        self.AC_Info.setObjectName(_fromUtf8("AC_Info"))
        self.AC_About = QtWidgets.QAction(MainWindow)
        self.AC_About.setObjectName(_fromUtf8("AC_About"))
        self.AC_Author = QtWidgets.QAction(MainWindow)
        self.AC_Author.setObjectName(_fromUtf8("AC_Author"))
        self.AC_EditWL = QtWidgets.QAction(MainWindow)
        self.AC_EditWL.setObjectName(_fromUtf8("AC_EditWL"))
        self.action_9 = QtWidgets.QAction(MainWindow)
        self.action_9.setObjectName(_fromUtf8("action_9"))
        self.menu.addAction(self.AC_Check)
        self.menu.addSeparator()
        self.menu.addAction(self.AC_Setting)
        self.menu_2.addAction(self.AC_CheckML)
        self.menu_2.addAction(self.AC_EditWL)
        self.menu_4.addAction(self.AC_Info)
        self.menu_4.addAction(self.AC_About)
        self.menu_4.addAction(self.AC_Author)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        #MainWindow.setWindowTitle(_translate("MainWindow", "Static Malware Analysis & Report Tool", None))
        MainWindow.setWindowTitle(_translate("MainWindow", "PyLance Artificial Intelligence Tool", None))
        #self.groupBox_4.setTitle(_translate("MainWindow", "参数设置", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Settings", None))
        #self.label_4.setText(_translate("MainWindow", "扫描规则：", None))
        self.label_4.setText(_translate("MainWindow", "Rules：", None))
        #self.CBRuleAll.setText(_translate("MainWindow", "全选", None))
        self.CBRuleAll.setText(_translate("MainWindow", "All", None))
        #self.CBRulePE.setText(_translate("MainWindow", "PE分析", None))
        self.CBRulePE.setText(_translate("MainWindow", "PE", None))
        #self.CBRuleCrypto.setText(_translate("MainWindow", "检查加密", None))
        self.CBRuleCrypto.setText(_translate("MainWindow", "Encryption", None))
        #self.CBRulePack.setText(_translate("MainWindow", "文件查壳", None))
        self.CBRulePack.setText(_translate("MainWindow", "ShellCode", None))
        #self.CBRuleSelf.setText(_translate("MainWindow", "自定义规则", None))
        self.CBRuleSelf.setText(_translate("MainWindow", "Custom", None))
        #self.CBRuleWL.setText(_translate("MainWindow", "启用白名单", None))
        self.CBRuleWL.setText(_translate("MainWindow", "Whitelist", None))
        #self.label_3.setText(_translate("MainWindow", "文件类型：", None))
        self.label_3.setText(_translate("MainWindow", "Files：", None))
        #self.CBTypeAll.setText(_translate("MainWindow", "全选", None))
        self.CBTypeAll.setText(_translate("MainWindow", "All", None))
        self.CBTypePE.setText(_translate("MainWindow", "PE", None))
        self.CBTypeOffice.setText(_translate("MainWindow", "Office", None))
        #self.CBTypeShell.setText(_translate("MainWindow", "脚本", None))
        self.CBTypeShell.setText(_translate("MainWindow", "Script", None))
        #self.CBTypeZip.setText(_translate("MainWindow", "压缩包", None))
        self.CBTypeZip.setText(_translate("MainWindow", "Archive", None))
        #self.CBTypeMedia.setText(_translate("MainWindow", "多媒体", None))
        self.CBTypeMedia.setText(_translate("MainWindow", "Multimedia", None))
        #self.CBTypeAsm.setText(_translate("MainWindow", "asm文件", None))
        self.CBTypeAsm.setText(_translate("MainWindow", "Assembly", None))
        #self.label_5.setText(_translate("MainWindow", "高级设置：", None))
        self.label_5.setText(_translate("MainWindow", "Advanced：", None))
        #self.lineEditAdvSet.setText(_translate("MainWindow", "当前未设置", None))
        self.lineEditAdvSet.setText(_translate("MainWindow", "Not Currently Set", None))
        #self.groupBox_3.setTitle(_translate("MainWindow", "操作区域", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Operations", None))
        #self.label.setText(_translate("MainWindow", "扫描起始：", None))
        self.label.setText(_translate("MainWindow", "Start：", None))
        #self.label_2.setText(_translate("MainWindow", "扫描策略：", None))
        self.label_2.setText(_translate("MainWindow", "Select：", None))
        #self.comboBox.setToolTip(_translate("MainWindow", "设置扫描策略", None))
        self.comboBox.setToolTip(_translate("MainWindow", "Choose Scan Policy", None))
        #self.comboBox.setItemText(0, _translate("MainWindow", "文件夹扫描", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "Folders", None))
        #self.comboBox.setItemText(1, _translate("MainWindow", "多文件扫描", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "Multiple Files", None))
        #self.label_6.setToolTip(_translate("MainWindow", "文件夹扫描深度设置，-1时全部扫描", None))
        self.label_6.setToolTip(_translate("MainWindow", "Depth Settings，-1 for All", None))
        #self.label_6.setText(_translate("MainWindow", "扫描深度：", None))
        self.label_6.setText(_translate("MainWindow", "Depth：", None))
        #self.spinBox.setToolTip(_translate("MainWindow", "文件夹扫描深度设置，-1时全部扫描", None))
        self.spinBox.setToolTip(_translate("MainWindow", "Depth Settings，-1 for All", None))
        #self.PB_SelectFolder.setText(_translate("MainWindow", "选择目标", None))
        self.PB_SelectFolder.setText(_translate("MainWindow", "Target", None))
        #self.PB_Start.setText(_translate("MainWindow", "开  始", None))
        self.PB_Start.setText(_translate("MainWindow", "Start", None))
        #self.PB_End.setText(_translate("MainWindow", "结  束", None))
        self.PB_End.setText(_translate("MainWindow", "Stop", None))
        #self.groupBox.setTitle(_translate("MainWindow", "显示策略", None))
        self.groupBox.setTitle(_translate("MainWindow", "Display", None))
        #self.label_7.setText(_translate("MainWindow", "模糊查询：", None))
        self.label_7.setText(_translate("MainWindow", "Value：", None))
        #self.label_8.setText(_translate("MainWindow", "查询列名：", None))
        self.label_8.setText(_translate("MainWindow", "Search：", None))
        #self.comboBox_2.setItemText(0, _translate("MainWindow", "name", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Name", None))
        #self.comboBox_2.setItemText(1, _translate("MainWindow", "type", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Type", None))
        #self.comboBox_2.setItemText(2, _translate("MainWindow", "md5", None))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "MD5", None))
        #self.PB_Select.setText(_translate("MainWindow", "查询", None))
        self.PB_Select.setText(_translate("MainWindow", "Search", None))
        #self.PB_Recover.setText(_translate("MainWindow", "恢  复", None))
        self.PB_Recover.setText(_translate("MainWindow", "Restore", None))
        #self.PB_Store.setText(_translate("MainWindow", "保  存", None))
        self.PB_Store.setText(_translate("MainWindow", "Save", None))
        #self.PB_Clear.setText(_translate("MainWindow", "清  空", None))
        self.PB_Clear.setText(_translate("MainWindow", "Clear", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Path", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Size", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Type", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Detection", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Mark", None))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Analysis Date", None))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "MD5", None))
        item = self.tableWidget.horizontalHeaderItem(8)
        #item.setText(_translate("MainWindow", "id", None))
        item.setText(_translate("MainWindow", "ID", None))
        #self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "扫描页面", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Scanning", None))
        #self.PB_KeepLog.setText(_translate("MainWindow", "保存报告", None))
        self.PB_KeepLog.setText(_translate("MainWindow", "Save Output", None))
        #self.PB_ClearLog.setText(_translate("MainWindow", "清空内容", None))
        self.PB_ClearLog.setText(_translate("MainWindow", "Clear Output", None))
        #self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "扫描报告", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Output", None))
        #self.groupBox_2.setTitle(_translate("MainWindow", "显示策略", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Display", None))
        #self.label_9.setText(_translate("MainWindow", "模糊查询：", None))
        self.label_9.setText(_translate("MainWindow", "Value：", None))
        #self.label_10.setText(_translate("MainWindow", "查询列名：", None))
        self.label_10.setText(_translate("MainWindow", "Search：", None))
        #self.comboBox_3.setItemText(0, _translate("MainWindow", "name", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Name", None))
        #self.comboBox_3.setItemText(1, _translate("MainWindow", "type", None))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Type", None))
        #self.comboBox_3.setItemText(2, _translate("MainWindow", "md5", None))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "MD5", None))
        #self.PB_SelectHistory.setText(_translate("MainWindow", "查询记录", None))
        self.PB_SelectHistory.setText(_translate("MainWindow", "Search", None))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Path", None))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Size", None))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Type", None))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Detection", None))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Mark", None))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Date", None))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "MD5", None))
        #self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "查看历史", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "History", None))
        #self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "调试", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Debug", None))
        #self.menu.setTitle(_translate("MainWindow", "管理", None))
        self.menu.setTitle(_translate("MainWindow", "Management", None))
        #self.menu_2.setTitle(_translate("MainWindow", "文件", None))
        self.menu_2.setTitle(_translate("MainWindow", "File", None))
        #self.menu_4.setTitle(_translate("MainWindow", "帮助", None))
        self.menu_4.setTitle(_translate("MainWindow", "Help", None))
        #self.AC_Check.setText(_translate("MainWindow", "检查配置", None))
        self.AC_Check.setText(_translate("MainWindow", "Check Configuration", None))
        #self.AC_Setting.setText(_translate("MainWindow", "软件设置", None))
        self.AC_Setting.setText(_translate("MainWindow", "Settings", None))
        #self.AC_CheckML.setText(_translate("MainWindow", "机器学习验证", None))
        self.AC_CheckML.setText(_translate("MainWindow", "Machine Learning", None))
        #self.AC_Info.setText(_translate("MainWindow", "版本信息", None))
        self.AC_Info.setText(_translate("MainWindow", "Version", None))
        #self.AC_About.setText(_translate("MainWindow", "关于软件", None))
        self.AC_About.setText(_translate("MainWindow", "About", None))
        #self.AC_Author.setText(_translate("MainWindow", "联系作者", None))
        self.AC_Author.setText(_translate("MainWindow", "Contact Author", None))
        #self.AC_EditWL.setText(_translate("MainWindow", "修改白名单", None))
        self.AC_EditWL.setText(_translate("MainWindow", "Edit Whitelist", None))
        #self.action_9.setText(_translate("MainWindow", "软件设置", None))
        self.action_9.setText(_translate("MainWindow", "Settings", None))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
